### PR TITLE
Use FQDN for builtin actions.

### PR DESCRIPTION
**Pull request by ixai**
Molecule tests are failing because lint requires FQDN for builtin actions.

### CODE REVIEW

**Comment by ixai** [comment]
I'm not able to get `molecule test` to pass locally, even when running it on a clean `master` branch. Any idea why this could be happening?

The failed task is the following:

```
TASK [ansible-zookeeper : Start the ZooKeeper service] *************************
fatal: [zookeeper-1]: FAILED! => {"changed": false, "cmd": "/bin/systemctl", "msg": "Failed to connect to bus: No such file or directory", "rc": 1, "stderr": "Failed to connect to bus: No such file or directory\n", "stderr_lines": ["Failed to connect to bus: No such file or directory"], "stdout": "", "stdout_lines": []}
fatal: [zookeeper-3]: FAILED! => {"changed": false, "cmd": "/usr/bin/systemctl", "msg": "Failed to connect to bus: No such file or directory", "rc": 1, "stderr": "Failed to connect to bus: No such file or directory\n", "stderr_lines": ["Failed to connect to bus: No such file or directory"], "stdout": "", "stdout_lines": []}
fatal: [zookeeper-2]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}
```

**Comment by sleighzy** [comment]
Hi @ixai . Can you confirm what version of Ansible you are using? At least one of those errors may be relevant to the note in the README about required Ansible versions due to some breaking changes in kernels and the status they are reporting for systemd. 

I'll try this locally on my end as soon as I get the chance to see if I get a similar result.

I've kicked off the github build which completed just now successfully so looks like that works with your changes now.

**Comment by ixai** [comment]
@sleighzy I hadn't paid attention to the notes on the README 😅 . I'm using ansible 2.12.4 in the virtualenv, I'll take a look at the related issues, but it's good to know the tests are passing in the CI environment.

**Comment by sleighzy** [comment]
2.12.4 should be fine. Out of curiosity what machine / OS are you running this on, e.g. macOS and the new laptops with the M1 chip?

**Comment by ixai** [comment]
I'm using macOS 12.3.1 on an Intel machine. I used Homebrew to install python3, ansible, and molecule first; but then created the venv and reinstalled ansible and molecule there.

Inside the venv, these are the versions that I get. The only odd thing I see is that `ansible --version` claims a different python version than the rest.

```
$ cat molecule-venv/pyvenv.cfg
home = /usr/local/opt/python@3.9/bin
include-system-site-packages = false
version = 3.9.12
```

```
$ molecule --version
molecule 3.6.1 using python 3.9
    ansible:2.12.4
    delegated:3.6.1 from molecule
    docker:1.1.0 from molecule_docker requiring collections: community.docker>=1.9.1
```

```
$ python --version
Python 3.9.12
```

```
$ ansible --version
ansible [core 2.12.4]
  config file = /Users/ixai/.ansible.cfg
  configured module search path = ['/Users/ixai/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/5.5.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/ixai/.ansible/collections:/usr/share/ansible/collections:/Users/ixai/repos
  executable location = /usr/local/bin/ansible
  python version = 3.10.2 (main, Feb  2 2022, 06:19:27) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.1.1
  libyaml = True
```

**Pull request merged**
